version: '3.9'
services:
  db_easy_find_java:
    image: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: easy_find_java
    ports:
      - 5432:5432
    volumes:
      - pgdata:/data/postgres


volumes:
  pgdata:
    driver: local